# Let's start with the basics: this is a PHP project
language: php

# Run on top of a few versions to check compatibility
matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: SEND_COVERAGE=1
    - php: 7.2
    - php: 7.3
  allow_failures:
    - php: nightly

# Install Composer package before testing
install:
  - composer install --no-interaction

# Run PHPUnit tests
script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml

# Send coverage to Codacy (just once per build)
after_success:
  - if [ "$SEND_COVERAGE" == "1" ]; then php vendor/bin/codacycoverage clover build/coverage/xml; fi
