# Let's start with the basics: this is a PHP project
language: php

# Disable email notifications for all builds
notifications:
  email: false

# Run on top of a few versions to check compatibility
matrix:
  fast_finish: true
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      env: SEND_COVERAGE=true TEST_WEBSERVICES=true
    - php: '8.0'
    - php: nightly
  allow_failures:
    - php: nightly

# Prepare environment
before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then unset SEND_COVERAGE; unset TEST_WEBSERVICES; fi

# Install Composer package before testing
install:
  - composer install --no-interaction

# Run PHPUnit tests
script:
  - XDEBUG_MODE=coverage vendor/bin/simple-phpunit

# Send coverage to Codacy (just once per build)
after_success:
  - if [ "$SEND_COVERAGE" == "true" ]; then bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r build/clover.xml; fi
